// <auto-generated />
using System;
using System.Collections.Generic;
using Banking.ClientAccounts.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banking.ClientAccounts.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250322200648_WWW")]
    partial class WWW
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ClientAccounts")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Banking.ClientAccounts.Domain.Aggregate.ClientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<int>("UserAccountType")
                        .HasColumnType("integer")
                        .HasColumnName("user_account_type");

                    b.HasKey("Id")
                        .HasName("pk_client_accounts");

                    b.ToTable("client_accounts", "ClientAccounts");
                });

            modelBuilder.Entity("Banking.ClientAccounts.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("client_account_id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<int>("Сurrency")
                        .HasColumnType("integer")
                        .HasColumnName("сurrency");

                    b.ComplexProperty<Dictionary<string, object>>("Balance", "Banking.ClientAccounts.Domain.Entities.Account.Balance#Balance", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasMaxLength(20)
                                .HasColumnType("double precision")
                                .HasColumnName("balance");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PaymentDetails", "Banking.ClientAccounts.Domain.Entities.Account.PaymentDetails#PaymentDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("payment_details");
                        });

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("client_account_id")
                        .HasDatabaseName("ix_accounts_client_account_id");

                    b.ToTable("accounts", "ClientAccounts");
                });

            modelBuilder.Entity("Banking.ClientAccounts.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<DateTime>("ValidThru")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validThru");

                    b.Property<Guid>("client_account_id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.ComplexProperty<Dictionary<string, object>>("Ccv", "Banking.ClientAccounts.Domain.Entities.Card.Ccv#Ccv", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ccv");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PaymentDetails", "Banking.ClientAccounts.Domain.Entities.Card.PaymentDetails#PaymentDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("payment_details");
                        });

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_cards_account_id");

                    b.HasIndex("client_account_id")
                        .HasDatabaseName("ix_cards_client_account_id");

                    b.ToTable("cards", "ClientAccounts");
                });

            modelBuilder.Entity("Banking.ClientAccounts.Domain.Entities.Account", b =>
                {
                    b.HasOne("Banking.ClientAccounts.Domain.Aggregate.ClientAccount", null)
                        .WithMany("Accounts")
                        .HasForeignKey("client_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_client_accounts_client_account_id");
                });

            modelBuilder.Entity("Banking.ClientAccounts.Domain.Entities.Card", b =>
                {
                    b.HasOne("Banking.ClientAccounts.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_accounts_account_id");

                    b.HasOne("Banking.ClientAccounts.Domain.Aggregate.ClientAccount", null)
                        .WithMany("Cards")
                        .HasForeignKey("client_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_client_accounts_client_account_id");
                });

            modelBuilder.Entity("Banking.ClientAccounts.Domain.Aggregate.ClientAccount", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
